/*
 * Hardware modules present on the AM335X chips
 *
 * Copyright (C) {2011} Texas Instruments Incorporated - http://www.ti.com/
 *
 * This file is automatically generated from the AM335X hardware databases.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation version 2.
 *
 * This program is distributed "as is" WITHOUT ANY WARRANTY of any
 * kind, whether express or implied; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */


#include <linux/io.h>

#include <plat/omap_hwmod.h>
#include <plat/cpu.h>
#include <plat/gpio.h>
#include <plat/dma.h>
#include <plat/mmc.h>

#include "omap_hwmod_common_data.h"

#include "cmam335x.h"
#include "prm-regbits-am335x.h"
#include "prmam335x.h"

/* XXX: In struct omap_hwmod, "masters" field has not been updated.
 * Code analysis so far didn't brought to notice any instance where
 * "masters" field would be used. It is not sure whether PM code
 * does use this field, PM code is yet to be explored to find it.
 * This leads to the question why link between interconnects has
 * been done in HWMOD database (for other SoC's), perhaps it may
 * be that dependency between interconnects are not implemented in
 * the present Kernel, but work may be proceeding in this direction,
 * more investigation would be required to ascertain this.
 */

/* Base offset for all AM335X interrupts external to MPUSS */
#define AM335X_IRQ_GIC_START	0

/* Base offset for all AM335X dma requests */
#define AM335X_DMA_REQ_START  1

/* Backward references (IPs with Bus Master capability) */
static struct omap_hwmod am335x_uart1_hwmod;
static struct omap_hwmod am335x_uart2_hwmod;
static struct omap_hwmod am335x_uart3_hwmod;
static struct omap_hwmod am335x_uart4_hwmod;
static struct omap_hwmod am335x_uart5_hwmod;
static struct omap_hwmod am335x_uart6_hwmod;
static struct omap_hwmod am335x_cpgmac0_hwmod;
static struct omap_hwmod am335x_icss_hwmod;
static struct omap_hwmod am335x_ieee5000_hwmod;
static struct omap_hwmod am335x_l4wkup_hwmod;
static struct omap_hwmod am335x_tptc0_hwmod;
static struct omap_hwmod am335x_tptc1_hwmod;
static struct omap_hwmod am335x_tptc2_hwmod;
static struct omap_hwmod am335x_usb0_hwmod;

	/*
	* Interconnects hwmod structures
	* hwmods that compose the global AM335X OCP interconnect
	*/

/* l4wkup interface data */
static struct omap_hwmod_class am335x_l4wkup_hwmod_class = {
	.name = "l4wkup",
};

static struct omap_hwmod am335x_l4wkup_hwmod = {
	.name		= "l4wkup",
	.class		= &am335x_l4wkup_hwmod_class,
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};


/* 'adc_tsc' class */

static struct omap_hwmod_class am335x_adc_tsc_hwmod_class = {
	.name = "adc_tsc",
};

/* adc_tsc */
static struct omap_hwmod_irq_info am335x_adc_tsc_irqs[] = {
	{ .irq = 115 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_adc_tsc_hwmod = {
	.name		= "adc_tsc",
	.class		= &am335x_adc_tsc_hwmod_class,
	.mpu_irqs       = am335x_adc_tsc_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_adc_tsc_irqs),
	.main_clk	= "adc_tsc_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_ADC_TSC_CLKCTRL,
		},
	},
};

/* 'aes' class */

static struct omap_hwmod_class am335x_aes_hwmod_class = {
	.name = "aes",
};

/* aes0 */
static struct omap_hwmod_irq_info am335x_aes0_irqs[] = {
	{ .irq = 102 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_aes0_hwmod = {
	.name		= "aes0",
	.class		= &am335x_aes_hwmod_class,
	.mpu_irqs       = am335x_aes0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_aes0_irqs),
	.main_clk	= "sysclk_div_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_AES0_CLKCTRL,
		},
	},
};

/* 'cefuse' class */

static struct omap_hwmod_class am335x_cefuse_hwmod_class = {
	.name = "cefuse",
};

/* cefuse */
static struct omap_hwmod am335x_cefuse_hwmod = {
	.name		= "cefuse",
	.class		= &am335x_cefuse_hwmod_class,
	.main_clk	= "cefuse_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_CEFUSE_CEFUSE_CLKCTRL,
		},
	},
};

/* 'clkdiv32k' class */

static struct omap_hwmod_class am335x_clkdiv32k_hwmod_class = {
	.name = "clkdiv32k",
};

/* clkdiv32k */

static struct omap_hwmod am335x_clkdiv32k_hwmod = {
	.name		= "clkdiv32k",
	.class		= &am335x_clkdiv32k_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_CLK_24MHZ_CLKSTCTRL,
		},
	},
};

/* 'control' class */

static struct omap_hwmod_class am335x_control_hwmod_class = {
	.name = "control",
};

/* control */
static struct omap_hwmod_irq_info am335x_control_irqs[] = {
	{ .irq = 8 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_control_hwmod = {
	.name		= "control",
	.class		= &am335x_control_hwmod_class,
	.mpu_irqs       = am335x_control_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_control_irqs),
	.main_clk	= "control_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_CONTROL_CLKCTRL,
		},
	},
};

/* 'cpgmac0' class */

static struct omap_hwmod_class am335x_cpgmac0_hwmod_class = {
	.name = "cpgmac0",
};

/* cpgmac0 */
static struct omap_hwmod am335x_cpgmac0_hwmod = {
	.name		= "cpgmac0",
	.class		= &am335x_cpgmac0_hwmod_class,
	.main_clk	= "cpsw_50m_clkdiv_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_CPGMAC0_CLKCTRL,
		},
	},
};

/* 'dcan' class */

static struct omap_hwmod_class am335x_dcan_hwmod_class = {
	.name = "dcan",
};

/* dcan0 */
static struct omap_hwmod_irq_info am335x_dcan0_irqs[] = {
	{ .irq = 52 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_dcan0_hwmod = {
	.name		= "dcan0",
	.class		= &am335x_dcan_hwmod_class,
	.mpu_irqs       = am335x_dcan0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_dcan0_irqs),
	.main_clk	= "sys_clkin_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_DCAN0_CLKCTRL,
		},
	},
};

/* dcan1 */
static struct omap_hwmod_irq_info am335x_dcan1_irqs[] = {
	{ .irq = 55 + AM335X_IRQ_GIC_START },
};
static struct omap_hwmod am335x_dcan1_hwmod = {
	.name		= "dcan1",
	.class		= &am335x_dcan_hwmod_class,
	.mpu_irqs       = am335x_dcan1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_dcan1_irqs),
	.main_clk	= "sys_clkin_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_DCAN1_CLKCTRL,
		},
	},
};

/* 'debugss' class */

static struct omap_hwmod_class am335x_debugss_hwmod_class = {
	.name = "debugss",
};

/* debugss */
static struct omap_hwmod am335x_debugss_hwmod = {
	.name		= "debugss",
	.class		= &am335x_debugss_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_DEBUGSS_CLKCTRL,
		},
	},
};

/* 'efuse' class */

static struct omap_hwmod_class am335x_efuse_hwmod_class = {
	.name = "efuse",
};

/* efuse */
static struct omap_hwmod am335x_efuse_hwmod = {
	.name		= "efuse",
	.class		= &am335x_efuse_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_CEFUSE_CEFUSE_CLKCTRL,
		},
	},
};

/* 'elm' class */

static struct omap_hwmod_class am335x_elm_hwmod_class = {
	.name = "elm",
};

/* elm */
static struct omap_hwmod am335x_elm_hwmod = {
	.name		= "elm",
	.class		= &am335x_elm_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_ELM_CLKCTRL,
		},
	},
};

/* 'emif_fw' class */

static struct omap_hwmod_class am335x_emif_fw_hwmod_class = {
	.name = "emif_fw",
};

/* emif_fw */
static struct omap_hwmod am335x_emif_fw_hwmod = {
	.name		= "emif_fw",
	.class		= &am335x_emif_fw_hwmod_class,
	.main_clk	= "core_100m_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_EMIF_FW_CLKCTRL,
		},
	},
};

/* 'epwmss' class */

static struct omap_hwmod_class am335x_epwmss_hwmod_class = {
	.name = "epwmss",
};

/* epwmss0 */
static struct omap_hwmod am335x_epwmss0_hwmod = {
	.name		= "epwmss0",
	.class		= &am335x_epwmss_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_EPWMSS0_CLKCTRL,
		},
	},
};

/* epwmss1 */
static struct omap_hwmod am335x_epwmss1_hwmod = {
	.name		= "epwmss1",
	.class		= &am335x_epwmss_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_EPWMSS1_CLKCTRL,
		},
	},
};

/* epwmss2 */
static struct omap_hwmod am335x_epwmss2_hwmod = {
	.name		= "epwmss2",
	.class		= &am335x_epwmss_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_EPWMSS2_CLKCTRL,
		},
	},
};

/* 'gpio' class */

static struct omap_hwmod_class am335x_gpio_hwmod_class = {
	.name = "gpio",
};

/* gpio0 */
static struct omap_hwmod am335x_gpio0_hwmod = {
	.name		= "gpio0",
	.class		= &am335x_gpio_hwmod_class,
	.main_clk	= "gpio0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_GPIO0_CLKCTRL,
		},
	},
};

/* gpio1 */
static struct omap_hwmod am335x_gpio1_hwmod = {
	.name		= "gpio1",
	.class		= &am335x_gpio_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_GPIO1_CLKCTRL,
		},
	},
};

/* gpio2 */
static struct omap_hwmod_irq_info am335x_gpio2_irqs[] = {
	{ .irq = 32 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_gpio2_hwmod = {
	.name		= "gpio2",
	.class		= &am335x_gpio_hwmod_class,
	.mpu_irqs       = am335x_gpio2_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_gpio2_irqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_GPIO2_CLKCTRL,
		},
	},
};

/* gpio3 */
static struct omap_hwmod am335x_gpio3_hwmod = {
	.name		= "gpio3",
	.class		= &am335x_gpio_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_GPIO3_CLKCTRL,
		},
	},
};

/* 'gpmc' class */

static struct omap_hwmod_class am335x_gpmc_hwmod_class = {
	.name = "gpmc",
};

/* gpmc */
static struct omap_hwmod am335x_gpmc_hwmod = {
	.name		= "gpmc",
	.class		= &am335x_gpmc_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_GPMC_CLKCTRL,
		},
	},
};

/* 'i2c' class */

static struct omap_hwmod_class am335x_i2c_hwmod_class = {
	.name = "i2c",
};

/* i2c0 */
static struct omap_hwmod_irq_info am335x_i2c0_irqs[] = {
	{ .irq = 70 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_i2c0_hwmod = {
	.name		= "i2c0",
	.class		= &am335x_i2c_hwmod_class,
	.mpu_irqs       = am335x_i2c0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_i2c0_irqs),
	.main_clk	= "i2c0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_I2C0_CLKCTRL,
		},
	},
};

/* i2c1 */
static struct omap_hwmod_irq_info am335x_i2c1_irqs[] = {
	{ .irq = 71 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_i2c1_hwmod = {
	.name		= "i2c1",
	.class		= &am335x_i2c_hwmod_class,
	.mpu_irqs       = am335x_i2c1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_i2c1_irqs),
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_I2C1_CLKCTRL,
		},
	},
};

/* i2c2 */
static struct omap_hwmod am335x_i2c2_hwmod = {
	.name		= "i2c2",
	.class		= &am335x_i2c_hwmod_class,
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_I2C2_CLKCTRL,
		},
	},
};

/* 'icss' class */

static struct omap_hwmod_class am335x_icss_hwmod_class = {
	.name = "icss",
};

/* icss */
static struct omap_hwmod am335x_icss_hwmod = {
	.name		= "icss",
	.class		= &am335x_icss_hwmod_class,
	.main_clk	= "dpll_per_m2_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_ICSS_CLKCTRL,
		},
	},
};

/* 'ieee5000' class */

static struct omap_hwmod_class am335x_ieee5000_hwmod_class = {
	.name = "ieee5000",
};

/* ieee5000 */
static struct omap_hwmod am335x_ieee5000_hwmod = {
	.name		= "ieee5000",
	.class		= &am335x_ieee5000_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_IEEE5000_CLKCTRL,
		},
	},
};

/* 'l3' class */

static struct omap_hwmod_class am335x_l3_hwmod_class = {
	.name = "l3",
};

/* l4_hs */
static struct omap_hwmod am335x_l4_hs_hwmod = {
	.name		= "l4_hs",
	.class		= &am335x_l3_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_L4HS_CLKCTRL,
		},
	},
};

/* l3_instr */
static struct omap_hwmod am335x_l3_instr_hwmod = {
	.name		= "l3_instr",
	.class		= &am335x_l3_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_L3_INSTR_CLKCTRL,
		},
	},
};

/* l3_main */
static struct omap_hwmod am335x_l3_main_hwmod = {
	.name		= "l3_main",
	.class		= &am335x_l3_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_L3_CLKCTRL,
		},
	},
};

/* 'l4fw' class */

static struct omap_hwmod_class am335x_l4fw_hwmod_class = {
	.name = "l4fw",
};

/* l4fw */
static struct omap_hwmod am335x_l4fw_hwmod = {
	.name		= "l4fw",
	.class		= &am335x_l4fw_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_L4FW_CLKCTRL,
		},
	},
};

/* 'l4ls' class */

static struct omap_hwmod_class am335x_l4ls_hwmod_class = {
	.name = "l4ls",
};

/* l4ls */
static struct omap_hwmod am335x_l4ls_hwmod = {
	.name		= "l4ls",
	.class		= &am335x_l4ls_hwmod_class,
	.main_clk	= "l4ls_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_L4LS_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'lcdc' class */

static struct omap_hwmod_class am335x_lcdc_hwmod_class = {
	.name = "lcdc",
};

/* lcdc */
static struct omap_hwmod_irq_info am335x_lcdc_irqs[] = {
	{ .irq = 36 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_lcdc_hwmod = {
	.name		= "lcdc",
	.class		= &am335x_lcdc_hwmod_class,
	.mpu_irqs       = am335x_lcdc_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_lcdc_irqs),
	.main_clk	= "lcd_clk_mux_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_LCDC_CLKCTRL,
		},
	},
};

/* 'mcasp' class */

static struct omap_hwmod_class am335x_mcasp_hwmod_class = {
	.name = "mcasp",
};

/* mcasp0 */
static struct omap_hwmod_irq_info am335x_mcasp0_irqs[] = {
	{ .irq = 80 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_mcasp0_hwmod = {
	.name		= "mcasp0",
	.class		= &am335x_mcasp_hwmod_class,
	.mpu_irqs       = am335x_mcasp0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_mcasp0_irqs),
	.main_clk	= "sys_clkin_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_MCASP0_CLKCTRL,
		},
	},
};

/* 'mlb' class */

static struct omap_hwmod_class am335x_mlb_hwmod_class = {
	.name = "mlb",
};

/* mlb */
static struct omap_hwmod am335x_mlb_hwmod = {
	.name		= "mlb",
	.class		= &am335x_mlb_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_MLB_CLKCTRL,
		},
	},
};

/* 'mmc' class */

static struct omap_hwmod_class am335x_mmc_hwmod_class = {
	.name = "mmc",
};

/* mmc0 */
static struct omap_hwmod_irq_info am335x_mmc0_irqs[] = {
	{ .irq = 64 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_mmc0_hwmod = {
	.name		= "mmc0",
	.class		= &am335x_mmc_hwmod_class,
	.mpu_irqs       = am335x_mmc0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_mmc0_irqs),
	.main_clk	= "mmc_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_MMC0_CLKCTRL,
		},
	},
};

/* mmc1 */
static struct omap_hwmod_irq_info am335x_mmc1_irqs[] = {
	{ .irq = 28 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_mmc1_hwmod = {
	.name		= "mmc1",
	.class		= &am335x_mmc_hwmod_class,
	.mpu_irqs       = am335x_mmc1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_mmc1_irqs),
	.main_clk	= "mmc_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_MMC1_CLKCTRL,
		},
	},
};

/* mmc2 */
static struct omap_hwmod_irq_info am335x_mmc2_irqs[] = {
	{ .irq = 29 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_mmc2_hwmod = {
	.name		= "mmc2",
	.class		= &am335x_mmc_hwmod_class,
	.mpu_irqs       = am335x_mmc2_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_mmc2_irqs),
	.main_clk	= "mmc_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_MMC2_CLKCTRL,
		},
	},
};

/* 'mpu' class */

static struct omap_hwmod_class am335x_mpu_hwmod_class = {
	.name = "mpu",
};

/* mpu */
static struct omap_hwmod am335x_mpu_hwmod = {
	.name		= "mpu",
	.class		= &am335x_mpu_hwmod_class,
	.flags		= (HWMOD_INIT_NO_IDLE | HWMOD_INIT_NO_RESET),
	.main_clk	= "mpu_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_MPU_MPU_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'ocmcram' class */

static struct omap_hwmod_class am335x_ocmcram_hwmod_class = {
	.name = "ocmcram",
};

/* ocmcram */
static struct omap_hwmod am335x_ocmcram_hwmod = {
	.name		= "ocmcram",
	.class		= &am335x_ocmcram_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_OCMCRAM_CLKCTRL,
		},
	},
};

/* 'ocpwp' class */

static struct omap_hwmod_class am335x_ocpwp_hwmod_class = {
	.name = "ocpwp",
};

/* ocpwp */
static struct omap_hwmod am335x_ocpwp_hwmod = {
	.name		= "ocpwp",
	.class		= &am335x_ocpwp_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_OCPWP_CLKCTRL,
		},
	},
};

/* 'rtc' class */

static struct omap_hwmod_class am335x_rtc_hwmod_class = {
	.name = "rtc",
};

/* rtc */
static struct omap_hwmod_irq_info am335x_rtc_irqs[] = {
	{ .irq = 75 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_rtc_hwmod = {
	.name		= "rtc",
	.class		= &am335x_rtc_hwmod_class,
	.mpu_irqs       = am335x_rtc_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_rtc_irqs),
	.main_clk	= "clk_32khz_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_RTC_RTC_CLKCTRL,
		},
	},
};

/* 'sha0' class */

static struct omap_hwmod_class am335x_sha0_hwmod_class = {
	.name = "sha0",
};

/* sha0 */
static struct omap_hwmod_irq_info am335x_sha0_irqs[] = {
	{ .irq = 108 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_sha0_hwmod = {
	.name		= "sha0",
	.class		= &am335x_sha0_hwmod_class,
	.mpu_irqs       = am335x_sha0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_sha0_irqs),
	.main_clk	= "sysclk_div_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_SHA0_CLKCTRL,
		},
	},
};

/* 'smartreflex' class */

static struct omap_hwmod_class am335x_smartreflex_hwmod_class = {
	.name = "smartreflex",
};

/* smartreflex0 */
static struct omap_hwmod_irq_info am335x_smartreflex0_irqs[] = {
	{ .irq = 120 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_smartreflex0_hwmod = {
	.name		= "smartreflex0",
	.class		= &am335x_smartreflex_hwmod_class,
	.mpu_irqs       = am335x_smartreflex0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_smartreflex0_irqs),
	.main_clk	= "smartreflex0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_SMARTREFLEX0_CLKCTRL,
		},
	},
};

/* smartreflex1 */
static struct omap_hwmod_irq_info am335x_smartreflex1_irqs[] = {
	{ .irq = 121 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_smartreflex1_hwmod = {
	.name		= "smartreflex1",
	.class		= &am335x_smartreflex_hwmod_class,
	.mpu_irqs       = am335x_smartreflex1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_smartreflex1_irqs),
	.main_clk	= "smartreflex1_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_SMARTREFLEX1_CLKCTRL,
		},
	},
};

/* 'spare' class */

static struct omap_hwmod_class am335x_spare_hwmod_class = {
	.name = "spare",
};

/* spare0 */
static struct omap_hwmod am335x_spare0_hwmod = {
	.name		= "spare0",
	.class		= &am335x_spare_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_SPARE0_CLKCTRL,
		},
	},
};

/* spare1 */
static struct omap_hwmod am335x_spare1_hwmod = {
	.name		= "spare1",
	.class		= &am335x_spare_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_SPARE1_CLKCTRL,
		},
	},
};

/* 'spi' class */

static struct omap_hwmod_class am335x_spi_hwmod_class = {
	.name = "spi",
};

/* spi0 */
static struct omap_hwmod_irq_info am335x_spi0_irqs[] = {
	{ .irq = 65 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_spi0_hwmod = {
	.name		= "spi0",
	.class		= &am335x_spi_hwmod_class,
	.mpu_irqs       = am335x_spi0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_spi0_irqs),
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_SPI0_CLKCTRL,
		},
	},
};

/* spi1 */
static struct omap_hwmod am335x_spi1_hwmod = {
	.name           = "spi0",
	.class          = &am335x_spi_hwmod_class,
	.main_clk       = "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_SPI1_CLKCTRL,
		},
	},
};

/* 'spinlock' class */

static struct omap_hwmod_class am335x_spinlock_hwmod_class = {
	.name = "spinlock",
};

/* spinlock */
static struct omap_hwmod am335x_spinlock_hwmod = {
	.name		= "spinlock",
	.class		= &am335x_spinlock_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_SPINLOCK_CLKCTRL,
		},
	},
};

/* 'timer' class */

static struct omap_hwmod_class am335x_timer_hwmod_class = {
	.name = "timer",
};

/* timer0 */
static struct omap_hwmod am335x_timer0_hwmod = {
	.name		= "timer0",
	.class		= &am335x_timer_hwmod_class,
	.main_clk	= "timer0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_TIMER0_CLKCTRL,
		},
	},
};

/* timer1 */
static struct omap_hwmod_irq_info am335x_timer1_irqs[] = {
	{ .irq = 67 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_timer1_hwmod = {
	.name		= "timer1",
	.class		= &am335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer1_irqs),
	.main_clk	= "timer1_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_TIMER1_CLKCTRL,
		},
	},
};

/* timer2 */
static struct omap_hwmod_irq_info am335x_timer2_irqs[] = {
	{ .irq = 68 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_timer2_hwmod = {
	.name		= "timer2",
	.class		= &am335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer2_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer2_irqs),
	.main_clk	= "timer2_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_TIMER2_CLKCTRL,
		},
	},
};

/* timer3 */
static struct omap_hwmod_irq_info am335x_timer3_irqs[] = {
	{ .irq = 69 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_timer3_hwmod = {
	.name		= "timer3",
	.class		= &am335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer3_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer3_irqs),
	.main_clk	= "timer3_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_TIMER3_CLKCTRL,
		},
	},
};

/* timer4 */
static struct omap_hwmod_irq_info am335x_timer4_irqs[] = {
	{ .irq = 92 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_timer4_hwmod = {
	.name		= "timer4",
	.class		= &am335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer4_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer4_irqs),
	.main_clk	= "timer4_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_TIMER4_CLKCTRL,
		},
	},
};

/* timer5 */
static struct omap_hwmod_irq_info am335x_timer5_irqs[] = {
	{ .irq = 93 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_timer5_hwmod = {
	.name		= "timer5",
	.class		= &am335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer5_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer5_irqs),
	.main_clk	= "timer5_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_TIMER5_CLKCTRL,
		},
	},
};

/* timer6 */
static struct omap_hwmod_irq_info am335x_timer6_irqs[] = {
	{ .irq = 94 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_timer6_hwmod = {
	.name		= "timer6",
	.class		= &am335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer6_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer6_irqs),
	.main_clk	= "timer6_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_TIMER6_CLKCTRL,
		},
	},
};

/* timer7 */
static struct omap_hwmod_irq_info am335x_timer7_irqs[] = {
	{ .irq = 95 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_timer7_hwmod = {
	.name		= "timer7",
	.class		= &am335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer7_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer7_irqs),
	.main_clk	= "timer7_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_TIMER7_CLKCTRL,
		},
	},
};

/* 'tpcc' class */

static struct omap_hwmod_class am335x_tpcc_hwmod_class = {
	.name = "tpcc",
};

/* tpcc */
static struct omap_hwmod_irq_info am335x_tpcc_irqs[] = {
	{ .irq = 12 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_tpcc_hwmod = {
	.name		= "tpcc",
	.class		= &am335x_tpcc_hwmod_class,
	.mpu_irqs       = am335x_tpcc_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_tpcc_irqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_TPCC_CLKCTRL,
		},
	},
};

/* 'tptc' class */

static struct omap_hwmod_class am335x_tptc_hwmod_class = {
	.name = "tptc",
};

/* tptc0 */
static struct omap_hwmod_irq_info am335x_tptc0_irqs[] = {
	{ .irq = 112 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_tptc0_hwmod = {
	.name		= "tptc0",
	.class		= &am335x_tptc_hwmod_class,
	.mpu_irqs       = am335x_tptc0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_tptc0_irqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_TPTC0_CLKCTRL,
		},
	},
};

/* tptc1 */
static struct omap_hwmod_irq_info am335x_tptc1_irqs[] = {
	{ .irq = 113 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_tptc1_hwmod = {
	.name		= "tptc1",
	.class		= &am335x_tptc_hwmod_class,
	.mpu_irqs       = am335x_tptc1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_tptc1_irqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_TPTC1_CLKCTRL,
		},
	},
};

/* tptc2 */
static struct omap_hwmod_irq_info am335x_tptc2_irqs[] = {
	{ .irq = 114 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_tptc2_hwmod = {
	.name		= "tptc2",
	.class		= &am335x_tptc_hwmod_class,
	.mpu_irqs       = am335x_tptc2_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_tptc2_irqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_TPTC2_CLKCTRL,
		},
	},
};

/* 'uart' class */

static struct omap_hwmod_class_sysconfig uart_sysc = {
	.rev_offs	= 0x50,
	.sysc_offs	= 0x54,
	.syss_offs	= 0x58,
	.sysc_flags	= (SYSC_HAS_SIDLEMODE |
			   SYSC_HAS_ENAWAKEUP | SYSC_HAS_SOFTRESET |
			   SYSC_HAS_AUTOIDLE),
	.idlemodes	= (SIDLE_FORCE | SIDLE_NO | SIDLE_SMART),
	.sysc_fields    = &omap_hwmod_sysc_type1,
};

static struct omap_hwmod_class uart_class = {
	.name = "uart",
	.sysc = &uart_sysc,
};

/* uart1 */

static struct omap_hwmod_dma_info uart1_edma_reqs[] = {
	{ .name = "tx",	.dma_req = 0, },
	{ .name = "rx",	.dma_req = 0, },
};

static struct omap_hwmod_addr_space am335x_uart1_addr_space[] = {
	{
		.pa_start	= AM335X_UART1_BASE,
		.pa_end		= AM335X_UART1_BASE + SZ_8K - 1,
		.flags		= ADDR_MAP_ON_INIT | ADDR_TYPE_RT,
	},
};

static struct omap_hwmod_ocp_if am335x_l4_wkup__uart1 = {
	.slave		= &am335x_uart1_hwmod,
	.clk		= "uart1_ick",
	.addr		= am335x_uart1_addr_space,
	.addr_cnt	= ARRAY_SIZE(am335x_uart1_addr_space),
	.user		= OCP_USER_MPU,
};

static struct omap_hwmod_irq_info am335x_uart1_irqs[] = {
	{ .irq = 72 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod_ocp_if *am335x_uart1_slaves[] = {
	&am335x_l4_wkup__uart1,
};

static struct omap_hwmod am335x_uart1_hwmod = {
	.name		= "uart1",
	.class		= &uart_class,
	.mpu_irqs       = am335x_uart1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart1_irqs),
	.sdma_reqs	= uart1_edma_reqs,
	.sdma_reqs_cnt	= ARRAY_SIZE(uart1_edma_reqs),
	.main_clk	= "uart1_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_UART0_CLKCTRL,
		},
	},
	.slaves		= am335x_uart1_slaves,
	.slaves_cnt	= ARRAY_SIZE(am335x_uart1_slaves),
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* uart2 */
static struct omap_hwmod_addr_space am335x_uart2_addr_space[] = {
	{
		.pa_start	= TI81XX_UART2_BASE,
		.pa_end		= TI81XX_UART2_BASE + SZ_8K - 1,
		.flags		= ADDR_MAP_ON_INIT | ADDR_TYPE_RT,
	},
};

static struct omap_hwmod_ocp_if am335x_l4_ls__uart2 = {
	.slave		= &am335x_uart2_hwmod,
	.clk		= "uart2_ick",
	.addr		= am335x_uart2_addr_space,
	.addr_cnt	= ARRAY_SIZE(am335x_uart2_addr_space),
	.user		= OCP_USER_MPU,
};

static struct omap_hwmod_irq_info am335x_uart2_irqs[] = {
	{ .irq = 73 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod_ocp_if *am335x_uart2_slaves[] = {
	&am335x_l4_ls__uart2,
};

static struct omap_hwmod am335x_uart2_hwmod = {
	.name		= "uart2",
	.class		= &uart_class,
	.mpu_irqs       = am335x_uart2_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart2_irqs),
	.main_clk	= "uart2_fck",
	.sdma_reqs	= uart1_edma_reqs,
	.sdma_reqs_cnt	= ARRAY_SIZE(uart1_edma_reqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_UART1_CLKCTRL,
		},
	},
	.slaves		= am335x_uart2_slaves,
	.slaves_cnt	= ARRAY_SIZE(am335x_uart2_slaves),
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* uart3 */
static struct omap_hwmod_addr_space am335x_uart3_addr_space[] = {
	{
		.pa_start	= TI81XX_UART3_BASE,
		.pa_end		= TI81XX_UART3_BASE + SZ_8K - 1,
		.flags		= ADDR_MAP_ON_INIT | ADDR_TYPE_RT,
	},
};

static struct omap_hwmod_ocp_if am335x_l4_ls__uart3 = {
	.slave		= &am335x_uart3_hwmod,
	.clk		= "uart3_ick",
	.addr		= am335x_uart3_addr_space,
	.addr_cnt	= ARRAY_SIZE(am335x_uart3_addr_space),
	.user		= OCP_USER_MPU,
};

static struct omap_hwmod_irq_info am335x_uart3_irqs[] = {
	{ .irq = 74 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod_ocp_if *am335x_uart3_slaves[] = {
	&am335x_l4_ls__uart3,
};

static struct omap_hwmod am335x_uart3_hwmod = {
	.name		= "uart3",
	.class		= &uart_class,
	.mpu_irqs       = am335x_uart3_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart3_irqs),
	.main_clk	= "uart3_fck",
	.sdma_reqs	= uart1_edma_reqs,
	.sdma_reqs_cnt	= ARRAY_SIZE(uart1_edma_reqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_UART2_CLKCTRL,
		},
	},
	.slaves		= am335x_uart3_slaves,
	.slaves_cnt	= ARRAY_SIZE(am335x_uart3_slaves),
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* uart4 */
static struct omap_hwmod_addr_space am335x_uart4_addr_space[] = {
	{
		.pa_start	= TI814X_UART4_BASE,
		.pa_end		= TI814X_UART4_BASE + SZ_8K - 1,
		.flags		= ADDR_MAP_ON_INIT | ADDR_TYPE_RT,
	},
};

static struct omap_hwmod_ocp_if am335x_l4_ls__uart4 = {
	.slave		= &am335x_uart4_hwmod,
	.clk		= "uart4_ick",
	.addr		= am335x_uart4_addr_space,
	.addr_cnt	= ARRAY_SIZE(am335x_uart4_addr_space),
	.user		= OCP_USER_MPU,
};

static struct omap_hwmod_irq_info am335x_uart4_irqs[] = {
	{ .irq = 44 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod_ocp_if *am335x_uart4_slaves[] = {
	&am335x_l4_ls__uart4,
};

static struct omap_hwmod am335x_uart4_hwmod = {
	.name		= "uart4",
	.class		= &uart_class,
	.mpu_irqs       = am335x_uart4_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart4_irqs),
	.main_clk	= "uart4_fck",
	.sdma_reqs	= uart1_edma_reqs,
	.sdma_reqs_cnt	= ARRAY_SIZE(uart1_edma_reqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_UART3_CLKCTRL,
		},
	},
	.slaves		= am335x_uart4_slaves,
	.slaves_cnt	= ARRAY_SIZE(am335x_uart4_slaves),
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* uart5 */
static struct omap_hwmod_addr_space am335x_uart5_addr_space[] = {
	{
		.pa_start	= TI814X_UART5_BASE,
		.pa_end		= TI814X_UART5_BASE + SZ_8K - 1,
		.flags		= ADDR_MAP_ON_INIT | ADDR_TYPE_RT,
	},
};

static struct omap_hwmod_ocp_if am335x_l4_ls__uart5 = {
	.slave		= &am335x_uart5_hwmod,
	.clk		= "uart5_ick",
	.addr		= am335x_uart5_addr_space,
	.addr_cnt	= ARRAY_SIZE(am335x_uart5_addr_space),
	.user		= OCP_USER_MPU,
};

static struct omap_hwmod_irq_info am335x_uart5_irqs[] = {
	{ .irq = 45 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod_ocp_if *am335x_uart5_slaves[] = {
	&am335x_l4_ls__uart5,
};

static struct omap_hwmod am335x_uart5_hwmod = {
	.name		= "uart5",
	.class		= &uart_class,
	.mpu_irqs       = am335x_uart5_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart5_irqs),
	.main_clk	= "uart5_fck",
	.sdma_reqs	= uart1_edma_reqs,
	.sdma_reqs_cnt	= ARRAY_SIZE(uart1_edma_reqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_UART4_CLKCTRL,
		},
	},
	.slaves		= am335x_uart5_slaves,
	.slaves_cnt	= ARRAY_SIZE(am335x_uart5_slaves),
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* uart6 */
static struct omap_hwmod_addr_space am335x_uart6_addr_space[] = {
	{
		.pa_start	= TI814X_UART6_BASE,
		.pa_end		= TI814X_UART6_BASE + SZ_8K - 1,
		.flags		= ADDR_MAP_ON_INIT | ADDR_TYPE_RT,
	},
};

static struct omap_hwmod_ocp_if am335x_l4_ls__uart6 = {
	.slave		= &am335x_uart6_hwmod,
	.clk		= "uart6_ick",
	.addr		= am335x_uart6_addr_space,
	.addr_cnt	= ARRAY_SIZE(am335x_uart6_addr_space),
	.user		= OCP_USER_MPU,
};

static struct omap_hwmod_irq_info am335x_uart6_irqs[] = {
	{ .irq = 46 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod_ocp_if *am335x_uart6_slaves[] = {
	&am335x_l4_ls__uart6,
};

static struct omap_hwmod am335x_uart6_hwmod = {
	.name		= "uart6",
	.class		= &uart_class,
	.mpu_irqs       = am335x_uart6_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart6_irqs),
	.main_clk	= "uart6_fck",
	.sdma_reqs	= uart1_edma_reqs,
	.sdma_reqs_cnt	= ARRAY_SIZE(uart1_edma_reqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_UART5_CLKCTRL,
		},
	},
	.slaves		= am335x_uart6_slaves,
	.slaves_cnt	= ARRAY_SIZE(am335x_uart6_slaves),
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'usb0' class */

static struct omap_hwmod_class am335x_usb0_hwmod_class = {
	.name = "usb0",
};

/* usb0 */
static struct omap_hwmod_irq_info am335x_usb0_irqs[] = {
	{ .irq = 18 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_usb0_hwmod = {
	.name		= "usb0",
	.class		= &am335x_usb0_hwmod_class,
	.mpu_irqs       = am335x_usb0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_usb0_irqs),
	.main_clk	= "core_100m_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_PER_USB0_CLKCTRL,
		},
	},
};

/* 'wd_timer1' class */

static struct omap_hwmod_class am335x_wd_timer1_hwmod_class = {
	.name = "wd_timer1",
};

/* wd_timer1 */
static struct omap_hwmod am335x_wd_timer1_hwmod = {
	.name		= "wd_timer1",
	.class		= &am335x_wd_timer1_hwmod_class,
	.main_clk	= "wd_timer1_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_WDT1_CLKCTRL,
		},
	},
};

/* 'wdt' class */

static struct omap_hwmod_class am335x_wdt_hwmod_class = {
	.name = "wdt",
};

/* wdt0 */
static struct omap_hwmod_irq_info am335x_wdt0_irqs[] = {
	{ .irq = 15 + AM335X_IRQ_GIC_START },
};

static struct omap_hwmod am335x_wdt0_hwmod = {
	.name		= "wdt0",
	.class		= &am335x_wdt_hwmod_class,
	.mpu_irqs       = am335x_wdt0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_wdt0_irqs),
	.main_clk	= "wdt0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_WDT0_CLKCTRL,
		},
	},
};

/* 'wkup_m3' class */

static struct omap_hwmod_class am335x_wkup_m3_hwmod_class = {
	.name = "wkup_m3",
};

/* wkup_m3 */
static struct omap_hwmod am335x_wkup_m3_hwmod = {
	.name		= "wkup_m3",
	.class		= &am335x_wkup_m3_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335X_CM_WKUP_WKUP_M3_CLKCTRL,
		},
	},
};

static __initdata struct omap_hwmod *am335x_hwmods[] = {
	/* l4wkup class */
	&am335x_l4wkup_hwmod,

	/* adc_tsc class */
	&am335x_adc_tsc_hwmod,
	/* aes class */
	&am335x_aes0_hwmod,
	/* cefuse class */
	&am335x_cefuse_hwmod,
	/* clkdiv32k class */
	&am335x_clkdiv32k_hwmod,
	/* control class */
	&am335x_control_hwmod,
	/* cpgmac0 class */
	&am335x_cpgmac0_hwmod,
	/* dcan class */
	&am335x_dcan0_hwmod,
	&am335x_dcan1_hwmod,
	/* debugss class */
	&am335x_debugss_hwmod,
	/* efuse class */
	&am335x_efuse_hwmod,
	/* elm class */
	&am335x_elm_hwmod,
	/* emif_fw class */
	&am335x_emif_fw_hwmod,
	/* epwmss class */
	&am335x_epwmss0_hwmod,
	&am335x_epwmss1_hwmod,
	&am335x_epwmss2_hwmod,
	/* gpio class */
	&am335x_gpio0_hwmod,
	&am335x_gpio1_hwmod,
	&am335x_gpio2_hwmod,
	&am335x_gpio3_hwmod,
	/* gpmc class */
	&am335x_gpmc_hwmod,
	/* i2c class */
	&am335x_i2c0_hwmod,
	&am335x_i2c1_hwmod,
	&am335x_i2c2_hwmod,
	/* icss class */
	&am335x_icss_hwmod,
	/* ieee5000 class */
	&am335x_ieee5000_hwmod,
	/* l3 class */
	&am335x_l4_hs_hwmod,
	&am335x_l3_instr_hwmod,
	&am335x_l3_main_hwmod,
	/* l4fw class */
	&am335x_l4fw_hwmod,
	/* l4ls class */
	&am335x_l4ls_hwmod,
	/* lcdc class */
	&am335x_lcdc_hwmod,
	/* mcasp class */
	&am335x_mcasp0_hwmod,
	/* mlb class */
	&am335x_mlb_hwmod,
	/* mmc class */
	&am335x_mmc0_hwmod,
	&am335x_mmc1_hwmod,
	&am335x_mmc2_hwmod,
	/* mpu class */
	&am335x_mpu_hwmod,
	/* ocmcram class */
	&am335x_ocmcram_hwmod,
	/* ocpwp class */
	&am335x_ocpwp_hwmod,
	/* rtc class */
	&am335x_rtc_hwmod,
	/* sha0 class */
	&am335x_sha0_hwmod,
	/* smartreflex class */
	&am335x_smartreflex0_hwmod,
	&am335x_smartreflex1_hwmod,
	/* spare class */
	&am335x_spare0_hwmod,
	&am335x_spare1_hwmod,
	/* spi class */
	&am335x_spi0_hwmod,
	&am335x_spi1_hwmod,
	/* spinlock class */
	&am335x_spinlock_hwmod,
	/* timer class */
	&am335x_timer0_hwmod,
	&am335x_timer1_hwmod,
	&am335x_timer2_hwmod,
	&am335x_timer3_hwmod,
	&am335x_timer4_hwmod,
	&am335x_timer5_hwmod,
	&am335x_timer6_hwmod,
	&am335x_timer7_hwmod,
	/* tpcc class */
	&am335x_tpcc_hwmod,
	/* tptc class */
	&am335x_tptc0_hwmod,
	&am335x_tptc1_hwmod,
	&am335x_tptc2_hwmod,
	/* uart class */
	&am335x_uart1_hwmod,
	&am335x_uart2_hwmod,
	&am335x_uart3_hwmod,
	&am335x_uart4_hwmod,
	&am335x_uart5_hwmod,
	&am335x_uart6_hwmod,
	/* usb0 class */
	&am335x_usb0_hwmod,
	/* wd_timer1 class */
	&am335x_wd_timer1_hwmod,
	/* wdt class */
	&am335x_wdt0_hwmod,
	/* wkup_m3 class */
	&am335x_wkup_m3_hwmod,
	NULL,
};

int __init am335x_hwmod_init(void)
{
	return omap_hwmod_init(am335x_hwmods);
}

