/*
 * Hardware modules present on the AM335x chips
 *
 * Copyright (C) {2011} Texas Instruments Incorporated - http://www.ti.com/
 *
 * This file is automatically generated from the AM335x hardware databases.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation version 2.
 *
 * This program is distributed "as is" WITHOUT ANY WARRANTY of any
 * kind, whether express or implied; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */


#include <linux/io.h>

#include <plat/omap_hwmod.h>
#include <plat/cpu.h>
#include <plat/gpio.h>
#include <plat/dma.h>
#include <plat/mmc.h>

#include "omap_hwmod_common_data.h"

#include "cmAM335x.h"
#include "prm-regbits-AM335x.h"
#include "prmAM335x.h"


/* Base offset for all AM335x interrupts external to MPUSS */
#define AM335x_IRQ_GIC_START	32

/* Base offset for all AM335x dma requests */
#define AM335x_DMA_REQ_START  1

/* Backward references (IPs with Bus Master capability) */
static struct omap_hwmod AM335x_cpgmac0_hwmod;
static struct omap_hwmod AM335x_icss_hwmod;
static struct omap_hwmod AM335x_ieee5000_hwmod;
static struct omap_hwmod AM335x_l4wkup_hwmod;
static struct omap_hwmod AM335x_tptc0_hwmod;
static struct omap_hwmod AM335x_tptc1_hwmod;
static struct omap_hwmod AM335x_tptc2_hwmod;
static struct omap_hwmod AM335x_usb0_hwmod;

	/*
	* Interconnects hwmod structures
	* hwmods that compose the global AM335x OCP interconnect
	*/

/* l4wkup interface data */
static struct omap_hwmod_class AM335x_l4wkup_hwmod_class = {
	.name = "l4wkup",
};

static struct omap_hwmod AM335x_l4wkup_hwmod = {
	.name		= "l4wkup",
	.class		= &AM335x_l4wkup_hwmod_class,
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};


/* 'adc_tsc' class */

static struct omap_hwmod_class AM335x_adc_tsc_hwmod_class = {
	.name = "adc_tsc",
};

/* adc_tsc */
static struct omap_hwmod_irq_info am335x_adc_tsc_irqs[] = {
	{ .irq = 115 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_adc_tsc_hwmod = {
	.name		= "adc_tsc",
	.class		= &AM335x_adc_tsc_hwmod_class,
	.mpu_irqs       = am335x_adc_tsc_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_adc_tsc_irqs),
	.main_clk	= "adc_tsc_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_ADC_TSC_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'aes' class */

static struct omap_hwmod_class AM335x_aes_hwmod_class = {
	.name = "aes",
};

/* aes0 */
static struct omap_hwmod_irq_info am335x_aes0_irqs[] = {
	{ .irq = 102 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_aes0_hwmod = {
	.name		= "aes0",
	.class		= &AM335x_aes_hwmod_class,
	.mpu_irqs       = am335x_aes0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_aes0_irqs),
	.main_clk	= "sysclk_div_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_AES0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'cefuse' class */

static struct omap_hwmod_class AM335x_cefuse_hwmod_class = {
	.name = "cefuse",
};

/* cefuse */
static struct omap_hwmod AM335x_cefuse_hwmod = {
	.name		= "cefuse",
	.class		= &AM335x_cefuse_hwmod_class,
	.main_clk	= "cefuse_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_CEFUSE_CEFUSE_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'clkdiv32k' class */

static struct omap_hwmod_class AM335x_clkdiv32k_hwmod_class = {
	.name = "clkdiv32k",
};

/* clkdiv32k */

static struct omap_hwmod AM335x_clkdiv32k_hwmod = {
	.name		= "clkdiv32k",
	.class		= &AM335x_clkdiv32k_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_CLK_24MHZ_CLKSTCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'control' class */

static struct omap_hwmod_class AM335x_control_hwmod_class = {
	.name = "control",
};

/* control */
static struct omap_hwmod_irq_info am335x_control_irqs[] = {
	{ .irq = 8 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_control_hwmod = {
	.name		= "control",
	.class		= &AM335x_control_hwmod_class,
	.mpu_irqs       = am335x_control_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_control_irqs),
	.main_clk	= "control_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_CONTROL_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'cpgmac0' class */

static struct omap_hwmod_class AM335x_cpgmac0_hwmod_class = {
	.name = "cpgmac0",
};

/* cpgmac0 */
static struct omap_hwmod AM335x_cpgmac0_hwmod = {
	.name		= "cpgmac0",
	.class		= &AM335x_cpgmac0_hwmod_class,
	.main_clk	= "cpsw_50m_clkdiv_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_CPGMAC0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'dcan' class */

static struct omap_hwmod_class AM335x_dcan_hwmod_class = {
	.name = "dcan",
};

/* dcan0 */
static struct omap_hwmod_irq_info am335x_dcan0_irqs[] = {
	{ .irq = 52 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_dcan0_hwmod = {
	.name		= "dcan0",
	.class		= &AM335x_dcan_hwmod_class,
	.mpu_irqs       = am335x_dcan0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_dcan0_irqs),
	.main_clk	= "sys_clkin_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_DCAN0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* dcan1 */
static struct omap_hwmod_irq_info am335x_dcan1_irqs[] = {
	{ .irq = 55 + AM335x_IRQ_GIC_START },
};
static struct omap_hwmod AM335x_dcan1_hwmod = {
	.name		= "dcan1",
	.class		= &AM335x_dcan_hwmod_class,
	.mpu_irqs       = am335x_dcan1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_dcan1_irqs),
	.main_clk	= "sys_clkin_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_DCAN1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'debugss' class */

static struct omap_hwmod_class AM335x_debugss_hwmod_class = {
	.name = "debugss",
};

/* debugss */
static struct omap_hwmod AM335x_debugss_hwmod = {
	.name		= "debugss",
	.class		= &AM335x_debugss_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_DEBUGSS_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'efuse' class */

static struct omap_hwmod_class AM335x_efuse_hwmod_class = {
	.name = "efuse",
};

/* efuse */
static struct omap_hwmod AM335x_efuse_hwmod = {
	.name		= "efuse",
	.class		= &AM335x_efuse_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_CEFUSE_CEFUSE_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'elm' class */

static struct omap_hwmod_class AM335x_elm_hwmod_class = {
	.name = "elm",
};

/* elm */
static struct omap_hwmod AM335x_elm_hwmod = {
	.name		= "elm",
	.class		= &AM335x_elm_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_ELM_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'emif_fw' class */

static struct omap_hwmod_class AM335x_emif_fw_hwmod_class = {
	.name = "emif_fw",
};

/* emif_fw */
static struct omap_hwmod AM335x_emif_fw_hwmod = {
	.name		= "emif_fw",
	.class		= &AM335x_emif_fw_hwmod_class,
	.main_clk	= "core_100m_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_EMIF_FW_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'epwmss' class */

static struct omap_hwmod_class AM335x_epwmss_hwmod_class = {
	.name = "epwmss",
};

/* epwmss0 */
static struct omap_hwmod AM335x_epwmss0_hwmod = {
	.name		= "epwmss0",
	.class		= &AM335x_epwmss_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_EPWMSS0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* epwmss1 */
static struct omap_hwmod AM335x_epwmss1_hwmod = {
	.name		= "epwmss1",
	.class		= &AM335x_epwmss_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_EPWMSS1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* epwmss2 */
static struct omap_hwmod AM335x_epwmss2_hwmod = {
	.name		= "epwmss2",
	.class		= &AM335x_epwmss_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_EPWMSS2_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'gpio' class */

static struct omap_hwmod_class AM335x_gpio_hwmod_class = {
	.name = "gpio",
};

/* gpio0 */
static struct omap_hwmod AM335x_gpio0_hwmod = {
	.name		= "gpio0",
	.class		= &AM335x_gpio_hwmod_class,
	.main_clk	= "gpio0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_GPIO0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* gpio1 */
static struct omap_hwmod AM335x_gpio1_hwmod = {
	.name		= "gpio1",
	.class		= &AM335x_gpio_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_GPIO1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* gpio2 */
static struct omap_hwmod_irq_info am335x_gpio2_irqs[] = {
	{ .irq = 32 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_gpio2_hwmod = {
	.name		= "gpio2",
	.class		= &AM335x_gpio_hwmod_class,
	.mpu_irqs       = am335x_gpio2_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_gpio2_irqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_GPIO2_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* gpio3 */
static struct omap_hwmod AM335x_gpio3_hwmod = {
	.name		= "gpio3",
	.class		= &AM335x_gpio_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_GPIO3_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'gpmc' class */

static struct omap_hwmod_class AM335x_gpmc_hwmod_class = {
	.name = "gpmc",
};

/* gpmc */
static struct omap_hwmod AM335x_gpmc_hwmod = {
	.name		= "gpmc",
	.class		= &AM335x_gpmc_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_GPMC_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'i2c' class */

static struct omap_hwmod_class AM335x_i2c_hwmod_class = {
	.name = "i2c",
};

/* i2c0 */
static struct omap_hwmod_irq_info am335x_i2c0_irqs[] = {
	{ .irq = 70 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_i2c0_hwmod = {
	.name		= "i2c0",
	.class		= &AM335x_i2c_hwmod_class,
	.mpu_irqs       = am335x_i2c0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_i2c0_irqs),
	.main_clk	= "i2c0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_I2C0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* i2c1 */
static struct omap_hwmod_irq_info am335x_i2c1_irqs[] = {
	{ .irq = 71 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_i2c1_hwmod = {
	.name		= "i2c1",
	.class		= &AM335x_i2c_hwmod_class,
	.mpu_irqs       = am335x_i2c1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_i2c1_irqs),
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_I2C1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* i2c2 */
static struct omap_hwmod AM335x_i2c2_hwmod = {
	.name		= "i2c2",
	.class		= &AM335x_i2c_hwmod_class,
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_I2C2_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'icss' class */

static struct omap_hwmod_class AM335x_icss_hwmod_class = {
	.name = "icss",
};

/* icss */
static struct omap_hwmod AM335x_icss_hwmod = {
	.name		= "icss",
	.class		= &AM335x_icss_hwmod_class,
	.main_clk	= "dpll_per_m2_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_ICSS_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'ieee5000' class */

static struct omap_hwmod_class AM335x_ieee5000_hwmod_class = {
	.name = "ieee5000",
};

/* ieee5000 */
static struct omap_hwmod AM335x_ieee5000_hwmod = {
	.name		= "ieee5000",
	.class		= &AM335x_ieee5000_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_IEEE5000_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'l3' class */

static struct omap_hwmod_class AM335x_l3_hwmod_class = {
	.name = "l3",
};

/* l4_hs */
static struct omap_hwmod AM335x_l4_hs_hwmod = {
	.name		= "l4_hs",
	.class		= &AM335x_l3_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_L4HS_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* l3_instr */
static struct omap_hwmod AM335x_l3_instr_hwmod = {
	.name		= "l3_instr",
	.class		= &AM335x_l3_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_L3_INSTR_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* l3_main */
static struct omap_hwmod AM335x_l3_main_hwmod = {
	.name		= "l3_main",
	.class		= &AM335x_l3_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_L3_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'l4fw' class */

static struct omap_hwmod_class AM335x_l4fw_hwmod_class = {
	.name = "l4fw",
};

/* l4fw */
static struct omap_hwmod AM335x_l4fw_hwmod = {
	.name		= "l4fw",
	.class		= &AM335x_l4fw_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_L4FW_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'l4ls' class */

static struct omap_hwmod_class AM335x_l4ls_hwmod_class = {
	.name = "l4ls",
};

/* l4ls */
static struct omap_hwmod AM335x_l4ls_hwmod = {
	.name		= "l4ls",
	.class		= &AM335x_l4ls_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_L4LS_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'lcdc' class */

static struct omap_hwmod_class AM335x_lcdc_hwmod_class = {
	.name = "lcdc",
};

/* lcdc */
static struct omap_hwmod_irq_info am335x_lcdc_irqs[] = {
	{ .irq = 36 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_lcdc_hwmod = {
	.name		= "lcdc",
	.class		= &AM335x_lcdc_hwmod_class,
	.mpu_irqs       = am335x_lcdc_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_lcdc_irqs),
	.main_clk	= "lcd_clk_mux_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_LCDC_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'mcasp' class */

static struct omap_hwmod_class AM335x_mcasp_hwmod_class = {
	.name = "mcasp",
};

/* mcasp0 */
static struct omap_hwmod_irq_info am335x_mcasp0_irqs[] = {
	{ .irq = 80 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_mcasp0_hwmod = {
	.name		= "mcasp0",
	.class		= &AM335x_mcasp_hwmod_class,
	.mpu_irqs       = am335x_mcasp0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_mcasp0_irqs),
	.main_clk	= "sys_clkin_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_MCASP0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'mlb' class */

static struct omap_hwmod_class AM335x_mlb_hwmod_class = {
	.name = "mlb",
};

/* mlb */
static struct omap_hwmod AM335x_mlb_hwmod = {
	.name		= "mlb",
	.class		= &AM335x_mlb_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_MLB_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'mmc' class */

static struct omap_hwmod_class AM335x_mmc_hwmod_class = {
	.name = "mmc",
};

/* mmc0 */
static struct omap_hwmod_irq_info am335x_mmc0_irqs[] = {
	{ .irq = 64 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_mmc0_hwmod = {
	.name		= "mmc0",
	.class		= &AM335x_mmc_hwmod_class,
	.mpu_irqs       = am335x_mmc0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_mmc0_irqs),
	.main_clk	= "mmc_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_MMC0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* mmc1 */
static struct omap_hwmod_irq_info am335x_mmc1_irqs[] = {
	{ .irq = 28 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_mmc1_hwmod = {
	.name		= "mmc1",
	.class		= &AM335x_mmc_hwmod_class,
	.mpu_irqs       = am335x_mmc1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_mmc1_irqs),
	.main_clk	= "mmc_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_MMC1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* mmc2 */
static struct omap_hwmod_irq_info am335x_mmc2_irqs[] = {
	{ .irq = 29 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_mmc2_hwmod = {
	.name		= "mmc2",
	.class		= &AM335x_mmc_hwmod_class,
	.mpu_irqs       = am335x_mmc2_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_mmc2_irqs),
	.main_clk	= "mmc_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_MMC2_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'mpu' class */

static struct omap_hwmod_class AM335x_mpu_hwmod_class = {
	.name = "mpu",
};

/* mpu */
static struct omap_hwmod AM335x_mpu_hwmod = {
	.name		= "mpu",
	.class		= &AM335x_mpu_hwmod_class,
	.main_clk	= "mpu_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_MPU_MPU_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'ocmcram' class */

static struct omap_hwmod_class AM335x_ocmcram_hwmod_class = {
	.name = "ocmcram",
};

/* ocmcram */
static struct omap_hwmod AM335x_ocmcram_hwmod = {
	.name		= "ocmcram",
	.class		= &AM335x_ocmcram_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_OCMCRAM_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'ocpwp' class */

static struct omap_hwmod_class AM335x_ocpwp_hwmod_class = {
	.name = "ocpwp",
};

/* ocpwp */
static struct omap_hwmod AM335x_ocpwp_hwmod = {
	.name		= "ocpwp",
	.class		= &AM335x_ocpwp_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_OCPWP_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'rtc' class */

static struct omap_hwmod_class AM335x_rtc_hwmod_class = {
	.name = "rtc",
};

/* rtc */
static struct omap_hwmod_irq_info am335x_rtc_irqs[] = {
	{ .irq = 75 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_rtc_hwmod = {
	.name		= "rtc",
	.class		= &AM335x_rtc_hwmod_class,
	.mpu_irqs       = am335x_rtc_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_rtc_irqs),
	.main_clk	= "clk_32khz_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_RTC_RTC_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'sha0' class */

static struct omap_hwmod_class AM335x_sha0_hwmod_class = {
	.name = "sha0",
};

/* sha0 */
static struct omap_hwmod_irq_info am335x_sha0_irqs[] = {
	{ .irq = 108 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_sha0_hwmod = {
	.name		= "sha0",
	.class		= &AM335x_sha0_hwmod_class,
	.mpu_irqs       = am335x_sha0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_sha0_irqs),
	.main_clk	= "sysclk_div_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_SHA0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'smartreflex' class */

static struct omap_hwmod_class AM335x_smartreflex_hwmod_class = {
	.name = "smartreflex",
};

/* smartreflex0 */
static struct omap_hwmod_irq_info am335x_smartreflex0_irqs[] = {
	{ .irq = 120 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_smartreflex0_hwmod = {
	.name		= "smartreflex0",
	.class		= &AM335x_smartreflex_hwmod_class,
	.mpu_irqs       = am335x_smartreflex0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_smartreflex0_irqs),
	.main_clk	= "smartreflex0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_SMARTREFLEX0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* smartreflex1 */
static struct omap_hwmod_irq_info am335x_smartreflex1_irqs[] = {
	{ .irq = 121 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_smartreflex1_hwmod = {
	.name		= "smartreflex1",
	.class		= &AM335x_smartreflex_hwmod_class,
	.mpu_irqs       = am335x_smartreflex1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_smartreflex1_irqs),
	.main_clk	= "smartreflex1_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_SMARTREFLEX1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'spare' class */

static struct omap_hwmod_class AM335x_spare_hwmod_class = {
	.name = "spare",
};

/* spare0 */
static struct omap_hwmod AM335x_spare0_hwmod = {
	.name		= "spare0",
	.class		= &AM335x_spare_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_SPARE0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* spare1 */
static struct omap_hwmod AM335x_spare1_hwmod = {
	.name		= "spare1",
	.class		= &AM335x_spare_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_SPARE1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'spi' class */

static struct omap_hwmod_class AM335x_spi_hwmod_class = {
	.name = "spi",
};

/* spi0 */
static struct omap_hwmod_irq_info am335x_spi0_irqs[] = {
	{ .irq = 65 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_spi0_hwmod = {
	.name		= "spi0",
	.class		= &AM335x_spi_hwmod_class,
	.mpu_irqs       = am335x_spi0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_spi0_irqs),
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_SPI0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* spi1 */
static struct omap_hwmod AM335x_spi1_hwmod = {
	.name           = "spi0",
	.class          = &AM335x_spi_hwmod_class,
	.main_clk       = "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_SPI1_CLKCTRL,
		},
	},
	.omap_chip      = OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'spinlock' class */

static struct omap_hwmod_class AM335x_spinlock_hwmod_class = {
	.name = "spinlock",
};

/* spinlock */
static struct omap_hwmod AM335x_spinlock_hwmod = {
	.name		= "spinlock",
	.class		= &AM335x_spinlock_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_SPINLOCK_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'timer' class */

static struct omap_hwmod_class AM335x_timer_hwmod_class = {
	.name = "timer",
};

/* timer0 */
static struct omap_hwmod AM335x_timer0_hwmod = {
	.name		= "timer0",
	.class		= &AM335x_timer_hwmod_class,
	.main_clk	= "timer0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_TIMER0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* timer1 */
static struct omap_hwmod_irq_info am335x_timer1_irqs[] = {
	{ .irq = 67 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_timer1_hwmod = {
	.name		= "timer1",
	.class		= &AM335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer1_irqs),
	.main_clk	= "timer1_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_TIMER1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* timer2 */
static struct omap_hwmod_irq_info am335x_timer2_irqs[] = {
	{ .irq = 68 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_timer2_hwmod = {
	.name		= "timer2",
	.class		= &AM335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer2_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer2_irqs),
	.main_clk	= "timer2_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_TIMER2_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* timer3 */
static struct omap_hwmod_irq_info am335x_timer3_irqs[] = {
	{ .irq = 69 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_timer3_hwmod = {
	.name		= "timer3",
	.class		= &AM335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer3_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer3_irqs),
	.main_clk	= "timer3_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_TIMER3_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* timer4 */
static struct omap_hwmod_irq_info am335x_timer4_irqs[] = {
	{ .irq = 92 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_timer4_hwmod = {
	.name		= "timer4",
	.class		= &AM335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer4_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer4_irqs),
	.main_clk	= "timer4_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_TIMER4_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* timer5 */
static struct omap_hwmod_irq_info am335x_timer5_irqs[] = {
	{ .irq = 93 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_timer5_hwmod = {
	.name		= "timer5",
	.class		= &AM335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer5_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer5_irqs),
	.main_clk	= "timer5_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_TIMER5_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* timer6 */
static struct omap_hwmod_irq_info am335x_timer6_irqs[] = {
	{ .irq = 94 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_timer6_hwmod = {
	.name		= "timer6",
	.class		= &AM335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer6_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer6_irqs),
	.main_clk	= "timer6_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_TIMER6_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* timer7 */
static struct omap_hwmod_irq_info am335x_timer7_irqs[] = {
	{ .irq = 95 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_timer7_hwmod = {
	.name		= "timer7",
	.class		= &AM335x_timer_hwmod_class,
	.mpu_irqs       = am335x_timer7_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_timer7_irqs),
	.main_clk	= "timer7_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_TIMER7_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'tpcc' class */

static struct omap_hwmod_class AM335x_tpcc_hwmod_class = {
	.name = "tpcc",
};

/* tpcc */
static struct omap_hwmod_irq_info am335x_tpcc_irqs[] = {
	{ .irq = 12 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_tpcc_hwmod = {
	.name		= "tpcc",
	.class		= &AM335x_tpcc_hwmod_class,
	.mpu_irqs       = am335x_tpcc_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_tpcc_irqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_TPCC_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'tptc' class */

static struct omap_hwmod_class AM335x_tptc_hwmod_class = {
	.name = "tptc",
};

/* tptc0 */
static struct omap_hwmod_irq_info am335x_tptc0_irqs[] = {
	{ .irq = 112 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_tptc0_hwmod = {
	.name		= "tptc0",
	.class		= &AM335x_tptc_hwmod_class,
	.mpu_irqs       = am335x_tptc0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_tptc0_irqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_TPTC0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* tptc1 */
static struct omap_hwmod_irq_info am335x_tptc1_irqs[] = {
	{ .irq = 113 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_tptc1_hwmod = {
	.name		= "tptc1",
	.class		= &AM335x_tptc_hwmod_class,
	.mpu_irqs       = am335x_tptc1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_tptc1_irqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_TPTC1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* tptc2 */
static struct omap_hwmod_irq_info am335x_tptc2_irqs[] = {
	{ .irq = 114 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_tptc2_hwmod = {
	.name		= "tptc2",
	.class		= &AM335x_tptc_hwmod_class,
	.mpu_irqs       = am335x_tptc2_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_tptc2_irqs),
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_TPTC2_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'uart' class */

static struct omap_hwmod_class AM335x_uart_hwmod_class = {
	.name = "uart",
};

/* uart0 */
static struct omap_hwmod_irq_info am335x_uart0_irqs[] = {
	{ .irq = 72 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_uart0_hwmod = {
	.name		= "uart0",
	.class		= &AM335x_uart_hwmod_class,
	.mpu_irqs       = am335x_uart0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart0_irqs),
	.main_clk	= "uart0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_UART0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* uart1 */
static struct omap_hwmod_irq_info am335x_uart1_irqs[] = {
	{ .irq = 73 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_uart1_hwmod = {
	.name		= "uart1",
	.class		= &AM335x_uart_hwmod_class,
	.mpu_irqs       = am335x_uart1_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart1_irqs),
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_UART1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* uart2 */
static struct omap_hwmod_irq_info am335x_uart2_irqs[] = {
	{ .irq = 74 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_uart2_hwmod = {
	.name		= "uart2",
	.class		= &AM335x_uart_hwmod_class,
	.mpu_irqs       = am335x_uart2_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart2_irqs),
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_UART2_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* uart3 */
static struct omap_hwmod_irq_info am335x_uart3_irqs[] = {
	{ .irq = 44 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_uart3_hwmod = {
	.name		= "uart3",
	.class		= &AM335x_uart_hwmod_class,
	.mpu_irqs       = am335x_uart3_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart3_irqs),
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_UART3_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* uart4 */
static struct omap_hwmod_irq_info am335x_uart4_irqs[] = {
	{ .irq = 45 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_uart4_hwmod = {
	.name		= "uart4",
	.class		= &AM335x_uart_hwmod_class,
	.mpu_irqs       = am335x_uart4_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart4_irqs),
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_UART4_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* uart5 */
static struct omap_hwmod_irq_info am335x_uart5_irqs[] = {
	{ .irq = 46 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_uart5_hwmod = {
	.name		= "uart5",
	.class		= &AM335x_uart_hwmod_class,
	.mpu_irqs       = am335x_uart5_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_uart5_irqs),
	.main_clk	= "i2c_clk",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_UART5_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'usb0' class */

static struct omap_hwmod_class AM335x_usb0_hwmod_class = {
	.name = "usb0",
};

/* usb0 */
static struct omap_hwmod_irq_info am335x_usb0_irqs[] = {
	{ .irq = 18 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_usb0_hwmod = {
	.name		= "usb0",
	.class		= &AM335x_usb0_hwmod_class,
	.mpu_irqs       = am335x_usb0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_usb0_irqs),
	.main_clk	= "core_100m_ck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_PER_USB0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'wd_timer1' class */

static struct omap_hwmod_class AM335x_wd_timer1_hwmod_class = {
	.name = "wd_timer1",
};

/* wd_timer1 */
static struct omap_hwmod AM335x_wd_timer1_hwmod = {
	.name		= "wd_timer1",
	.class		= &AM335x_wd_timer1_hwmod_class,
	.main_clk	= "wd_timer1_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_WDT1_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'wdt' class */

static struct omap_hwmod_class AM335x_wdt_hwmod_class = {
	.name = "wdt",
};

/* wdt0 */
static struct omap_hwmod_irq_info am335x_wdt0_irqs[] = {
	{ .irq = 15 + AM335x_IRQ_GIC_START },
};

static struct omap_hwmod AM335x_wdt0_hwmod = {
	.name		= "wdt0",
	.class		= &AM335x_wdt_hwmod_class,
	.mpu_irqs       = am335x_wdt0_irqs,
	.mpu_irqs_cnt   = ARRAY_SIZE(am335x_wdt0_irqs),
	.main_clk	= "wdt0_fck",
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_WDT0_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

/* 'wkup_m3' class */

static struct omap_hwmod_class AM335x_wkup_m3_hwmod_class = {
	.name = "wkup_m3",
};

/* wkup_m3 */
static struct omap_hwmod AM335x_wkup_m3_hwmod = {
	.name		= "wkup_m3",
	.class		= &AM335x_wkup_m3_hwmod_class,
	.prcm = {
		.omap4 = {
			.clkctrl_reg = AM335x_CM_WKUP_WKUP_M3_CLKCTRL,
		},
	},
	.omap_chip	= OMAP_CHIP_INIT(CHIP_IS_AM335X),
};

static __initdata struct omap_hwmod *am335x_hwmods[] = {
	/* l4wkup class */
	&AM335x_l4wkup_hwmod,

	/* adc_tsc class */
	&AM335x_adc_tsc_hwmod,
	/* aes class */
	&AM335x_aes0_hwmod,
	/* cefuse class */
	&AM335x_cefuse_hwmod,
	/* clkdiv32k class */
	&AM335x_clkdiv32k_hwmod,
	/* control class */
	&AM335x_control_hwmod,
	/* cpgmac0 class */
	&AM335x_cpgmac0_hwmod,
	/* dcan class */
	&AM335x_dcan0_hwmod,
	&AM335x_dcan1_hwmod,
	/* debugss class */
	&AM335x_debugss_hwmod,
	/* efuse class */
	&AM335x_efuse_hwmod,
	/* elm class */
	&AM335x_elm_hwmod,
	/* emif_fw class */
	&AM335x_emif_fw_hwmod,
	/* epwmss class */
	&AM335x_epwmss0_hwmod,
	&AM335x_epwmss1_hwmod,
	&AM335x_epwmss2_hwmod,
	/* gpio class */
	&AM335x_gpio0_hwmod,
	&AM335x_gpio1_hwmod,
	&AM335x_gpio2_hwmod,
	&AM335x_gpio3_hwmod,
	/* gpmc class */
	&AM335x_gpmc_hwmod,
	/* i2c class */
	&AM335x_i2c0_hwmod,
	&AM335x_i2c1_hwmod,
	&AM335x_i2c2_hwmod,
	/* icss class */
	&AM335x_icss_hwmod,
	/* ieee5000 class */
	&AM335x_ieee5000_hwmod,
	/* l3 class */
	&AM335x_l4_hs_hwmod,
	&AM335x_l3_instr_hwmod,
	&AM335x_l3_main_hwmod,
	/* l4fw class */
	&AM335x_l4fw_hwmod,
	/* l4ls class */
	&AM335x_l4ls_hwmod,
	/* lcdc class */
	&AM335x_lcdc_hwmod,
	/* mcasp class */
	&AM335x_mcasp0_hwmod,
	/* mlb class */
	&AM335x_mlb_hwmod,
	/* mmc class */
	&AM335x_mmc0_hwmod,
	&AM335x_mmc1_hwmod,
	&AM335x_mmc2_hwmod,
	/* mpu class */
	&AM335x_mpu_hwmod,
	/* ocmcram class */
	&AM335x_ocmcram_hwmod,
	/* ocpwp class */
	&AM335x_ocpwp_hwmod,
	/* rtc class */
	&AM335x_rtc_hwmod,
	/* sha0 class */
	&AM335x_sha0_hwmod,
	/* smartreflex class */
	&AM335x_smartreflex0_hwmod,
	&AM335x_smartreflex1_hwmod,
	/* spare class */
	&AM335x_spare0_hwmod,
	&AM335x_spare1_hwmod,
	/* spi class */
	&AM335x_spi0_hwmod,
	&AM335x_spi1_hwmod,
	/* spinlock class */
	&AM335x_spinlock_hwmod,
	/* timer class */
	&AM335x_timer0_hwmod,
	&AM335x_timer1_hwmod,
	&AM335x_timer2_hwmod,
	&AM335x_timer3_hwmod,
	&AM335x_timer4_hwmod,
	&AM335x_timer5_hwmod,
	&AM335x_timer6_hwmod,
	&AM335x_timer7_hwmod,
	/* tpcc class */
	&AM335x_tpcc_hwmod,
	/* tptc class */
	&AM335x_tptc0_hwmod,
	&AM335x_tptc1_hwmod,
	&AM335x_tptc2_hwmod,
	/* uart class */
	&AM335x_uart0_hwmod,
	&AM335x_uart1_hwmod,
	&AM335x_uart2_hwmod,
	&AM335x_uart3_hwmod,
	&AM335x_uart4_hwmod,
	&AM335x_uart5_hwmod,
	/* usb0 class */
	&AM335x_usb0_hwmod,
	/* wd_timer1 class */
	&AM335x_wd_timer1_hwmod,
	/* wdt class */
	&AM335x_wdt0_hwmod,
	/* wkup_m3 class */
	&AM335x_wkup_m3_hwmod,
	NULL,
};

int __init am335x_hwmod_init(void)
{
	return omap_hwmod_init(am335x_hwmods);
}

