/*
 * AM335x Powerdomain control
 *
 * This file is automatically generated from the AM335X hardware databases.
 *
 * Copyright (C) {YEAR} Texas Instruments Incorporated - http://www.ti.com/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation version 2.
 *
 * This program is distributed "as is" WITHOUT ANY WARRANTY of any
 * kind, whether express or implied; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include <linux/io.h>
#include <linux/errno.h>
#include <linux/delay.h>

#include "powerdomain.h"
#include <plat/prcm.h>
#include "prmAM335x.h"
#include "prm-regbits-AM335x.h"
#include "prminstAM335x.h"


static int am335x_pwrdm_set_next_pwrst(struct powerdomain *pwrdm, u8 pwrst)
{
	am335x_prminst_rmw_inst_reg_bits(OMAP_POWERSTATE_MASK,
					(pwrst << OMAP_POWERSTATE_SHIFT),
					pwrdm->prcm_partition,
					pwrdm->prcm_offs, AM335x_PM_PWSTCTRL);
	return 0;
}

static int am335x_pwrdm_read_next_pwrst(struct powerdomain *pwrdm)
{
	u32 v;

	v = am335x_prminst_read_inst_reg(pwrdm->prcm_partition,
					pwrdm->prcm_offs, AM335x_PM_PWSTCTRL);
	v &= OMAP_POWERSTATE_MASK;
	v >>= OMAP_POWERSTATE_SHIFT;

	return v;
}

static int am335x_pwrdm_read_pwrst(struct powerdomain *pwrdm)
{
	u32 v;

	v = am335x_prminst_read_inst_reg(pwrdm->prcm_partition,
					pwrdm->prcm_offs, AM335x_PM_PWSTST);
	v &= OMAP_POWERSTATEST_MASK;
	v >>= OMAP_POWERSTATEST_SHIFT;

	return v;
}

static int am335x_pwrdm_read_prev_pwrst(struct powerdomain *pwrdm)
{
	u32 v;

	v = am335x_prminst_read_inst_reg(pwrdm->prcm_partition,
					pwrdm->prcm_offs, AM335x_PM_PWSTST);
	v &= AM335x_LASTPOWERSTATEENTERED_MASK;
	v >>= AM335x_LASTPOWERSTATEENTERED_SHIFT;

	return v;
}

static int am335x_pwrdm_set_lowpwrstchange(struct powerdomain *pwrdm)
{
	am335x_prminst_rmw_inst_reg_bits(AM335x_LOWPOWERSTATECHANGE_MASK,
					(1 << AM335x_LOWPOWERSTATECHANGE_SHIFT),
					pwrdm->prcm_partition,
					pwrdm->prcm_offs, AM335x_PM_PWSTCTRL);
	return 0;
}

static int am335x_pwrdm_clear_all_prev_pwrst(struct powerdomain *pwrdm)
{
	am335x_prminst_rmw_inst_reg_bits(AM335x_LASTPOWERSTATEENTERED_MASK,
					AM335x_LASTPOWERSTATEENTERED_MASK,
					pwrdm->prcm_partition,
					pwrdm->prcm_offs, AM335x_PM_PWSTST);
	return 0;
}

static int am335x_pwrdm_set_logic_retst(struct powerdomain *pwrdm, u8 pwrst)
{
	u32 v;

	v = pwrst << __ffs(AM335x_LOGICRETSTATE_MASK);
	am335x_prminst_rmw_inst_reg_bits(AM335x_LOGICRETSTATE_MASK, v,
					pwrdm->prcm_partition, pwrdm->prcm_offs,
					AM335x_PM_PWSTCTRL);

	return 0;
}

static int am335x_pwrdm_set_mem_onst(struct powerdomain *pwrdm, u8 bank,
				    u8 pwrst)
{
	u32 m;

	m = omap2_pwrdm_get_mem_bank_onstate_mask(bank);

	am335x_prminst_rmw_inst_reg_bits(m, (pwrst << __ffs(m)),
					pwrdm->prcm_partition, pwrdm->prcm_offs,
					AM335x_PM_PWSTCTRL);

	return 0;
}

static int am335x_pwrdm_set_mem_retst(struct powerdomain *pwrdm, u8 bank,
				     u8 pwrst)
{
	u32 m;

	m = omap2_pwrdm_get_mem_bank_retst_mask(bank);

	am335x_prminst_rmw_inst_reg_bits(m, (pwrst << __ffs(m)),
					pwrdm->prcm_partition, pwrdm->prcm_offs,
					AM335x_PM_PWSTCTRL);

	return 0;
}

static int am335x_pwrdm_read_logic_pwrst(struct powerdomain *pwrdm)
{
	u32 v;

	v = am335x_prminst_read_inst_reg(pwrdm->prcm_partition,
				pwrdm->prcm_offs, AM335x_PM_PWSTST);
	v &= AM335x_LOGICSTATEST_MASK;
	v >>= AM335x_LOGICSTATEST_SHIFT;

	return v;
}

static int am335x_pwrdm_read_logic_retst(struct powerdomain *pwrdm)
{
	u32 v;

	v = am335x_prminst_read_inst_reg(pwrdm->prcm_partition,
				pwrdm->prcm_offs, AM335x_PM_PWSTCTRL);
	v &= AM335x_LOGICRETSTATE_MASK;
	v >>= AM335x_LOGICRETSTATE_SHIFT;

	return v;
}

static int am335x_pwrdm_read_mem_pwrst(struct powerdomain *pwrdm, u8 bank)
{
	u32 m, v;

	m = omap2_pwrdm_get_mem_bank_stst_mask(bank);

	v = am335x_prminst_read_inst_reg(pwrdm->prcm_partition,
				pwrdm->prcm_offs, AM335x_PM_PWSTST);
	v &= m;
	v >>= __ffs(m);

	return v;
}

static int am335x_pwrdm_read_mem_retst(struct powerdomain *pwrdm, u8 bank)
{
	u32 m, v;

	m = omap2_pwrdm_get_mem_bank_retst_mask(bank);

	v = am335x_prminst_read_inst_reg(pwrdm->prcm_partition,
				pwrdm->prcm_offs, AM335x_PM_PWSTCTRL);
	v &= m;
	v >>= __ffs(m);

	return v;
}

static int am335x_pwrdm_wait_transition(struct powerdomain *pwrdm)
{
	u32 c = 0;

	/*
	 * REVISIT: pwrdm_wait_transition() may be better implemented
	 * via a callback and a periodic timer check -- how long do we expect
	 * powerdomain transitions to take?
	 */

	/* XXX Is this udelay() value meaningful? */
	while ((am335x_prminst_read_inst_reg(pwrdm->prcm_partition,
					    pwrdm->prcm_offs,
					    AM335x_PM_PWSTST) &
		OMAP_INTRANSITION_MASK) &&
	       (c++ < PWRDM_TRANSITION_BAILOUT))
		udelay(1);

	if (c > PWRDM_TRANSITION_BAILOUT) {
		printk(KERN_ERR "powerdomain: waited too long for "
		       "powerdomain %s to complete transition\n", pwrdm->name);
		return -EAGAIN;
	}

	pr_debug("powerdomain: completed transition in %d loops\n", c);

	return 0;
}

struct pwrdm_ops am335x_pwrdm_operations = {
	.pwrdm_set_next_pwrst	= am335x_pwrdm_set_next_pwrst,
	.pwrdm_read_next_pwrst	= am335x_pwrdm_read_next_pwrst,
	.pwrdm_read_pwrst	= am335x_pwrdm_read_pwrst,
	.pwrdm_read_prev_pwrst	= am335x_pwrdm_read_prev_pwrst,
	.pwrdm_set_lowpwrstchange	= am335x_pwrdm_set_lowpwrstchange,
	.pwrdm_clear_all_prev_pwrst	= am335x_pwrdm_clear_all_prev_pwrst,
	.pwrdm_set_logic_retst	= am335x_pwrdm_set_logic_retst,
	.pwrdm_read_logic_pwrst	= am335x_pwrdm_read_logic_pwrst,
	.pwrdm_read_logic_retst	= am335x_pwrdm_read_logic_retst,
	.pwrdm_read_mem_pwrst	= am335x_pwrdm_read_mem_pwrst,
	.pwrdm_read_mem_retst	= am335x_pwrdm_read_mem_retst,
	.pwrdm_set_mem_onst	= am335x_pwrdm_set_mem_onst,
	.pwrdm_set_mem_retst	= am335x_pwrdm_set_mem_retst,
	.pwrdm_wait_transition	= am335x_pwrdm_wait_transition,
};
