/*
 * AM335X PRCM definitions
 *
 * This file is automatically generated from the AM335X hardware databases.
 *
 * Copyright (C) {YEAR} Texas Instruments Incorporated - http://www.ti.com/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation version 2.
 *
 * This program is distributed "as is" WITHOUT ANY WARRANTY of any
 * kind, whether express or implied; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef __ARCH_ARM_MACH_OMAP2_PRCMAM335X_H
#define __ARCH_ARM_MACH_OMAP2_PRCMAM335X_H

/*
 * OMAP4 PRCM partition IDs
 *
 * The numbers and order are arbitrary, but 0 is reserved for the
 * 'invalid' partition in case someone forgets to add a
 * .prcm_partition field.
 */
#define AM335x_INVALID_PRCM_PARTITION		0
#define AM335x_PRM_PARTITION			1
#define AM335x_CM_PARTITION                     2
#define AM335x_SCRM_PARTITION			3
#define AM335x_PRCM_MPU_PARTITION		4

/*
 * OMAP4_MAX_PRCM_PARTITIONS: set to the highest value of the PRCM partition
 * IDs, plus one
 */
#define AM335x_MAX_PRCM_PARTITIONS		5


#endif
